[package]
name = "express"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2018"

[dependencies]
fast-float = "0.2"
memchr = "2.7"
nom = "6"

[dev-dependencies]
clap = "3"
