[package]
name = "nurbs"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
nalgebra-glm = "0.18"
num-integer = "0.1"
ordered-float = "4"
smallvec = "1.6"
