[package]
name = "nurbs"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2024"

[dependencies]
log = "0.4"
nalgebra-glm = "0.20"
num-integer = "0.1"
ordered-float = "5"
smallvec = "1"
